dist: xenial
language: c
os:
  - linux

addons:
  apt:
    update: true
    sources:
      - ppa:snaipewastaken/ppa
    packages:
      - libpcap-dev
    
notifications:
  email: false
  
script:
  - make