dist: bionic
language: c
os:
  - linux

notifications:
  email: false

before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install criterion-dev libpcap-dev uthash-dev -y

script:
  - make

after_install:
  - cd test && make && quic_test.out